written test for the issue anf it is failing
ipajen/Webshop pull request #32
Opened 2024-11-25 08:43 UTC by BarnaliD

Test is failing ,addTocart button is not clicking

2024-11-27 21:34 UTC, BarnaliD commented
Cleaned the code and it works now

2024-11-28 08:10 UTC, ib222dp requested changes

2024-11-28 08:10 UTC, ib222dp commented on src/test/java/CheckWebshopStepDefinition.java
> +        //((JavascriptExecutor) driver).executeScript("window.scrollTo(0,"+addToCartButton.getLocation().y+")");
You can remove this commented out line

2024-11-28 08:24 UTC, ib222dp approved these changes

2024-11-28 08:33 UTC, ipajen approved these changes

2024-11-28 08:33 UTC, ipajen commented
the topic should be changed from " written test for the issue anf it is failing #32" to what it does..

2024-11-28 08:42 UTC, merged